### ISSUE TITLE
Wire Result Scanner into ZAP Pipeline

### ISSUE THREAD

**Issue by ctro** [18F/concourse-compliance-testing#24]
Tracking what's needed for this trello card:
https://trello.com/c/b3QE1wod/67-as-a-user-i-want-to-be-notified-if-my-zap-alerts-change
- [x] Blocked by 18F/s3-resource-simple#5
- [x] Download and Rename last `results` from S3
- [x] Move Result Scanner into `tasks/`, add a README, etc.
- [x] Run Result Scanner over last+current.  
- [ ] Address CodeClimate violations for ResultScanner

**Comment by afeld** [comment]
Just FYI that Trello supports checklists, in case you weren't aware:

http://help.trello.com/article/737-adding-checklists-to-cards

**Comment by DavidEBest** [comment]
This is good to close, correct, @ctro? Feel free to reopen if there are still code climate violations to address.

**Comment by ctro** [comment]
Good to close, thanks!
