### ISSUE TITLE
filter-team-data is case sensitive, but it shouldn't be?

### ISSUE THREAD

**Issue by DavidEBest** [18F/concourse-compliance-testing#33]
I added `c2` in the targets.json, which caused me to get 

```
WARN: `c2` is missing from Team API data.
```

in Concourse.

The project's name in the Team API is `C2`. Confusingly (but only tangentially related), `https://team-api.18f.gov/public/api/projects/C2/` returns a 404, but `https://team-api.18f.gov/public/api/projects/c2/` returns successfully.

**Comment by ctro** [comment]
I noticed the case sensitivity earlier.  I was also confused/unaware that C2==micropurchase.  Would some sort of :nickname field be useful for projects like this?  Or is it just better to "fix" this in the datasource?

**Comment by DavidEBest** [comment]
c2 isn't micropurchase, but it enables micropurchasing. :) It is also known as cap, though.

**Comment by ctro** [comment]
Well, that clears some things up :) Looking back at code, I think I confused myself when I started using the teamAPI + targets.json locally.  Looking at the current API data I'm not sure how I even connected the two in the first place.  :/    Anyhoo, thanks for setting me straight!

**Comment by DavidEBest** [comment]
I'd prefer to 'fix' it when we see it by lowercasing the `name` field when we pull them in. `name` is a bit of a misnomer; about.yml defines the field as:

> "This is a short name of your project that can be used as a URL slug."

(https://github.com/18F/about_yml/blob/master/lib/about_yml/schema.json#L9)

The `full_name` field should be used as the display name for the project.

I had to do something similar for the dashboard (https://github.com/18F/dashboard/commit/451fb5dc74a48e5a0db25c2b49e1b930a5e2b068) and this has been a thorn in the side of team api for a while (https://github.com/18F/team-api.18f.gov/pull/174).

Other thoughts, @afeld, @ctro?

**Comment by ctro** [comment]
:+1: for downcasing `name`

**Comment by DavidEBest** [comment]
Closed by #38.
