### ISSUE TITLE
atf-eregs scan hangs creating a new ZAP session.

### ISSUE THREAD

**Issue by DavidEBest** [18F/concourse-compliance-testing#48]
We saw this problem before, when we were relying on the `new session` command to loop over all the projects. When I ran `fly intercept` I found that it was stuck in ZAP, attempting to create a new session.

The ATF project consists of two VERY LARGE sites. I feel that there might be a bug with the new session creation code when there is a lot of data in the previous session. A possible work around/test to run would be to remove the `new session` mechanism, and just recreate the ZAP instance for every site. That'll incur a greater startup penalty, but that is less of a concern now that we aren't looping over all the projects within a single session.

http://ci-tooling.cloud.gov/pipelines/zap/jobs/zap-scheduled-atf-eregs/builds/1

https://trello.com/c/od2IZwIu/134-atf-eregs-scan-hangs-creating-a-new-zap-session

**Comment by afeld** [comment]
#50 seems to have done the trick:

https://ci-tooling.cloud.gov/pipelines/zap/jobs/zap-ondemand-atf-eregs/builds/1
