### ISSUE TITLE
Scanning OpenOpps failed with a seemingly random error.

### ISSUE THREAD

**Issue by DavidEBest** [18F/concourse-compliance-testing#49]
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to fetch digest: 401 Unauthorized
```

This sort of error appears to be a random docker/concourse error, not related to the actual job of running scans. Is this something that we can catch or retry?

http://ci-tooling.cloud.gov/pipelines/zap/jobs/zap-scheduled-openopps/builds/1
https://trello.com/c/5FGAUZtq/135-increase-reliability-of-individual-scans

**Comment by afeld** [comment]
Hmm, passed as [an ondemand build](https://ci-tooling.cloud.gov/pipelines/zap/jobs/zap-ondemand-openopps/builds/2)...not sure why that error appeared there, since it seemed to be in a task, not a resource.

**Comment by DavidEBest** [comment]
This might be a snipe hunt - seems like an intermittent/random error. Keeping this open so we can keep an eye on the possible error.

**Comment by DavidEBest** [comment]
Federalist had the same problem last night. http://ci.cloud.gov/pipelines/zap/jobs/zap-scheduled-federalist/builds/3

**Comment by afeld** [comment]
Seems like this may have been failures to fetch the Docker images?

**Comment by afeld** [comment]
https://github.com/docker/hub-feedback/issues/647

**Comment by afeld** [comment]
Closing as stale.
