### ISSUE TITLE
clean up repository

### ISSUE THREAD

**Issue by afeld** [18F/concourse-compliance-testing#5]
- [x] Remove unused tasks/pipelines
- [x] Put tasks/pipelines into respective folders

@DavidEBest Happy to help with this – any quick pointers on which aren't needed?

**Comment by DavidEBest** [comment]
@afeld I think #7 should resolve this. I created the following folders:
1) `pipelines`
2) `tasks`
3) `scripts` - the script files called by the tasks
4) `tools` - functions to do something in a non-concourse fashion, like the s3 multi-uploader.

If you think that's overkill, we could try something else.

**Comment by afeld** [comment]
Nope, that's perfect!
