### ISSUE TITLE
test the tests

### ISSUE THREAD

**Issue by afeld** [18F/concourse-compliance-testing#6]
Would be really nice to be able to automatically verify that a pipeline works in a pull request (and have the commit status updated), without needing to take the contributor's word for it or pulling down and running the pipeline locally. Not sure how difficult this would be to do.

**Comment by DavidEBest** [comment]
We might be able to build something with https://github.com/jtarchie/pullrequest-resource and the concourse API that'll do that. Not super straightforward, and could be problematic with a) credentials/secrets and b) things that actually deploy a service.

**Comment by afeld** [comment]
https://trello.com/c/pLxprDOH/87-come-up-with-a-test-plan-for-the-concourse-pipeline-repository

**Comment by afeld** [comment]
Closed by #40.
