### ISSUE TITLE
Add a mechanism to support badges for projects scanned via the compliance pipeline.

### ISSUE THREAD

**Issue by DavidEBest** [18F/concourse-compliance-testing#80]
Almost all of the repos provide 'at a glance' information for static code analysis (Code Climate, Quantified Code, etc) via a badging mechanism. The same should be possible for ZAP scan information.

**Comment by afeld** [comment]
Issue moved to [18F/compliance-viewer #77](https://github.com/18F/compliance-viewer/issues/77) via [**ZenHub**](https://www.zenhub.com/)
