### ISSUE TITLE
Investigate running CodeClimate VMs via the Concourse.CI environment.

### ISSUE THREAD

**Issue by DavidEBest** [18F/concourse-compliance-testing#83]
There are several standardized Code Climate scanning engines that _should_ be compatible with Concourse.CI, given recent changes (https://github.com/codeclimate/codeclimate/issues/299#issuecomment-198031232). When/if we move to do more static code analysis in house it'd be beneficial to use them.

**Comment by afeld** [comment]
_If_ we can get the scan result data out of Code Climate, I'm 👎 on this, since there's already a platform that works, and I don't think we get a lot of benefit out of duplicating functionality.

**Comment by afeld** [comment]
Closing for now since Code Climate is working fine, but we can re-open if there's a need.
