### ISSUE TITLE
Add cloud.gov sites to scheduled scans

### ISSUE THREAD

**Issue by dlapiduz** [18F/concourse-compliance-testing#89]
Can we add:
- [x] cloud.gov
- [x] login.cloud.gov / uaa.cloud.gov
- [x] docs.cloud.gov
- [x] logs.cloud.gov
- [x] ci.cloud.gov
- [x] api.cloud.gov
- [x] console.cloud.gov
- [x] metrics.cloud.gov
- [x] community.cloud.gov

To the regular scans?

Thanks!

**Comment by afeld** [comment]
Is the list above still accurate?
